update
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Oyefusi-Samuel/ZED-mobile-cleaning-simulated-robot..git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
	new file:   robot/src/drive_to_point/log/build_2023-06-07_00-18-29/events.log
To https://github.com/Oyefusi-Samuel/ZED-mobile-cleaning-simulated-robot..git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Oyefusi-Samuel/ZED-mobile-cleaning-simulated-robot..git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.